const stations = [
  'Jatinegara',
  'Pondok Jati',
  'Kramat',
  'Gang Sentiong',
  'Pasar Senen',
  'Kemayoran',
  'Rajawali',
  'Kampung Bandan',
  'Angke',
  'Duri',
  'Tanah Abang',
  'Karet',
  'Sudirman',
  'Manggarai',
  'Tebet',
  'Cawang',
  'Duren Kalibata',
  'Pasar Minggu Baru',
  'Pasar Minggu',
  'Tanjung Barat',
  'Lenteng Agung',
  'Universitas Pancasila',
  'Universitas Indonesia',
  'Pondok Cina',
  'Depok Baru',
  'Depok',
  'Citayam',
  'Bojonggede',
  'Cilebut',
  'Bogor',
  'Cibinong',
  'Nambo'
]

export default [stations, 'FDB813', 'Lingkar']
